# Generated by Django 5.2.15 on 2026-06-30 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockin',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='stockin',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockin', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockin', to='inventory.supplier'),
        ),
    ]
